### ISSUE TITLE
About Working of this

### ISSUE THREAD

**Issue by kappu1996** [tarunbatta/excelexportjs#48]
Tarun,

I used your earlier version and it was quite good and simple to use but today I came here to find out an issue but it seems like you updated it a lot and now it's looking quite complex so can you please provide me a basic example containing How to export from HTML to excel with complete processes because earlier version was quite easy to configure rather the this.
Please help me on high priority for this.
My Email ID-> Kapil1996Goyal@gmail.com

I look forward to hearing from you.

Kapil

**Comment by tarunbatta** [comment]
Hi Kapil,

The previous version was jQuery based, and a lot of folks wanted improvements in the same. Therefore, I created the new version which is object oriented, (in order to support latest frameworks like AngularJs, React, etc).

You can either use it with your TypeScript code, or you can use the JavaScript by requireJs in your project. I am sure you will figure that part out.

Also, there is a sample usage example in the readme. Please refer to the same.
Hope it helps.

Regards
Tarun
