### ISSUE TITLE
How to Use This as this looks very complex as compare to previous version

### ISSUE THREAD

**Issue by kappu1996** [tarunbatta/excelexportjs#49]
Hi Tarun,

Greetings from my side. Hope you are doing well.
Actually in previous version we just call the excelexportjs function with containerd ID and other attributes and it works perfectly but here i am not getting why you define column and row data in readme file so can you please help me how can i use this javascript file to export my table with some id.
Please revert me back as this is on higher priority for me.

Thanks Tarun.
I look forward to hear form you.

Kapil
(Kapil1996Goyal@gmail.com)

**Comment by tarunbatta** [comment]
Hi Kapil,

If you wish to use the previous version, please use the following link to download the code,
https://github.com/tarunbatta/excelexportjs/tree/3.0.1

Unfortunately, I would not be adding features or fixing issues to 3.0.1 tag, since it was using data URI feature of browser, so it had its fair share of limitations. But if you wish to enhance it, please feel free to fork it.

Based on the feedback from the community, I have already added the asked features on the 4.x version.

In the sample code in Readme file, we are defining columns and its respective schema. Further json array data is set to row data, along with any styling (if required). 

If you are facing any issues with with 4.x version, please feel free to share your sample code on JsFiddle along with detailed issue. I will definitely, look into that.

Regards
Tarun

**Comment by kappu1996** [comment]
Hi Tarun,
Thanks for your detailed response and giving time.
Actually being a software engineer i totally understand your concern that you released latest version which overcome multiple problems and works more effectively.
Actually thing is in my case i can't fix the table schema because data is coming on HTML from one tool and that is dynamic so we can't define data and in earlier version we only define table id and rest is done by your JS file including spanning , colors etc. everything.
So my concern is Can i use this version just by using Table ID again like in previous way ? And if it looks not possible then i have 2-3 problems related with previous version and if you can help me through them it would be great help from your side.
I look forward to hearing from you.

Thanks Tarun.

Kapil

**Comment by tarunbatta** [comment]
Hi Kapil,

Based on your requirement, I have added the feature to convert html table to exportexcel dataset object. Please use 4.0.3 version, and there is a sample example in the readme as well.

This feature though, comes with a limitation, that all cell types will be considered as string. I haven't thoroughly tested it, but I have a feeling it will work for your case.

In case you face any issues, please let me know.

Regards
Tarun
